branch: master
cleanTmp: false
tmpDir: "./repositories"
outputDir: "./"
dataDir: "./"
repositories:
  - url: https://github.com/makamekm/git-log-calendar-teams.git
    branch: master
    exclude:
      - cicd
  - url: https://github.com/makamekm/figma-react.git
    branch: develop
    exclude:
      - cicd
teams:
  - name: grid
    users:
      - makame
      - makame@mail.ru
    exclude:
      - cicd
    output: "team.svg"
  - name: others
    invert: true
    exclude:
      - cicd
    output: "others.svg"