branch: master
cleanTmp: false
tmpDir: "./repositories"
outputDir: "./"
statsDir: "./"
repositories:
  - url: https://github.com/makamekm/git-log-calendar-teams.git
    branch: master
    exclude:
      - cicd
  - url: https://github.com/makamekm/figma-react.git
    branch: develop
    exclude:
      - cicd
  - url: https://github.com/facebook/react.git
    branch: master
teams:
  - name: team
    users:
      - dan.abramov@gmail.com
      - makame
      - makame@mail.ru
    exclude:
      - cicd
    output: "team.svg"
    compare:
      - others
  - name: others
    invert: true
    exclude:
      - cicd
    output: "others.svg"
    compare:
      - team