branch: master
cleanTmp: false
debug: true
tmpDir: ./repositories
statsDir: ./

repositories:
  - url: https://github.com/makamekm/git-log-calendar-teams.git
    name: git-log-calendar-teams
    branch: master
  - url: https://github.com/makamekm/figma-react.git
    name: figma-react
    branch: develop
    exclude:
      - cicd
  - url: https://github.com/facebook/react.git
    name: react
    branch: master

users:
  - name: Maxim Karpov
    associations:
      - makame
      - makame@mail.ru
      - Maxim Karpov
      - Karpov Maxim

teams:
  - name: team
    users:
      - dan.abramov@gmail.com
      - Maxim Karpov
    # exclude:
    #   - cicd
  - name: others
    invert: true
    # exclude:
    #   - cicd

reportCalendarTeam:
  - team: team
    output: ./team.svg
    compareTeams:
      - others
  - team: others
    output: ./others.svg
    compareTeams:
      - team

# NOT IMPLEMENTED
reportCalendarUser:
  - user: Maxim Karpov
    limit: 20
    output: ./mkarpov.svg
  - user: Maxim Karpov
    repositories:
      - git-log-calendar-teams
    output: ./mkarpov-git-log.svg

# NOT IMPLEMENTED
reportDonutUser:
  - users:
      - Maxim Karpov
      - _others_
    output: ./mkarpov-total.svg
  - users:
      - dan.abramov@gmail.com
      - _others_
    repositories:
      - react
    output: ./danabramov-react-total.svg
  - limit: 365
    repositories:
      - react
    output: ./react-year.svg

# NOT IMPLEMENTED
reportMapUser:
  output: ./connections.svg